### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by techie2000** [SimonFair/unraid.usbip#5]
Looking at the files in the package `/boot/config/plugins/Usb_manager_usbip_addon/package/5.10.28/usbip-plugin-5.10.28-Unraid-1.txz`, the permissions would appear to be overly generous: 

```
lrwxrwxrwx root/root         0 2021-04-07 23:45 usr/lib64/libusbip.so -> libusbip.so.0.0.1
lrwxrwxrwx root/root         0 2021-04-07 23:45 usr/lib64/libusbip.so.0 -> libusbip.so.0.0.1
```

Should they be `rwxr-xr-x` or `rw-r--r--` in a future release (I appreciate that not many updates take place so this will not likely happen overnight 😃 ).

**Comment by ich777** [comment]
@techie2000 if I'm not mistaken these are symlinks and the permissions are always like this.
Do something like: `ls -la /usr/lib64` and you will see that symlinks always have that permissions or better speaking they inherit the permissions from the target.

If you got any further questions feel free to ask.

@SimonFair I think this can be closed...

**Comment by SimonFair** [comment]
thanks. Yes other files in the dir are the same.
